Update docs
JuliaSmoothOptimizers/OptimizationProblems.jl pull request #171
Opened 2022-04-29 17:33 UTC by tmigot

We can now use the `meta` to get the names of the problems for PureJuMP and ADNLPProblems.

I fixed some more typos when updating the benchmark.

2022-04-30 00:35 UTC, dpo requested changes

2022-04-30 00:35 UTC, dpo commented on docs/src/benchmark.md
> +Note that it is also possible to select the problems when initializing the problem list by searching into the `OptimizationProblems.meta`.
```suggestion
It is also possible to select problems when initializing the problem list by filtering `OptimizationProblems.meta`.
```

2022-04-30 00:35 UTC, dpo commented on docs/src/tutorial.md
> +You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]` that returns the list of exported names of the submodule.
```suggestion
You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]`.
```

2022-04-30 00:35 UTC, dpo commented on docs/src/tutorial.md
> +Note that some of these problems are scalable, i.e., their size depends on some parameters that can be modified. The list is available once again using the `meta`.
```suggestion
Note that certain problems are scalable, i.e., their size depends on parameters that can be modified. The list of those problems is available once again using `meta`.
```

2022-04-30 00:35 UTC, dpo commented on docs/src/tutorial.md
> +You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]` that returns the list of exported names of the submodule.
```suggestion
You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]`.
```

2022-05-02 13:44 UTC, tmigot commented
Thanks @dpo  for the comments. I merged them directly.

2022-05-02 22:55 UTC, dpo reviewed
Looks great, thank you! Just a couple of very minor things. Go ahead and merge after those.

2022-05-02 22:55 UTC, dpo commented on docs/src/benchmark.md
> +It is also possible to select problems when initializing the problem list by filtering `OptimizationProblems.meta`.
```suggestion
It is also possible to select problems when initializing the problem list by filtering `OptimizationProblems.meta`:
```

2022-05-02 22:55 UTC, dpo commented on docs/src/tutorial.md
> +Note that certain problems are scalable, i.e., their size depends on parameters that can be modified. The list of those problems is available once again using `meta`.
```suggestion
Note that certain problems are scalable, i.e., their size depends on parameters that can be modified. The list of those problems is available once again using `meta`:
```

2022-05-02 22:55 UTC, dpo commented on docs/src/tutorial.md
> +You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]`.
```suggestion
You can obtain the list of problems currently defined with `OptimizationProblems.meta[!, :name]`:
```

2022-05-02 23:56 UTC, merged