particles_distribution
JuliaSmoothOptimizers/OptimizationProblems.jl pull request #177
Opened 2022-05-13 18:48 UTC by nathanemac

Add particles_distribution

2022-05-14 13:39 UTC, dpo requested changes

2022-05-14 13:39 UTC, dpo commented on src/ADNLPProblems/particles_distribution.jl
> +        s=sum(u_elts)
This can be written without creating `u_elts`.

2022-05-14 13:39 UTC, dpo commented on src/ADNLPProblems/particles_distribution.jl
> +        v=reshape(x,3,N)'
```suggestion
        v=reshape(x, N, 3)
```

2022-05-18 13:42 UTC, tmigot requested changes
Thanks @nathanemac , good job! I have a couple of small comments.

2022-05-18 13:42 UTC, tmigot commented on src/Meta/particles_distribution.jl
> +particles_distribution_meta = Dict(
What happened here? It seems you have two files in the Meta. One (the generated one) misses the .jl, while the other seems incomplete `" ⋯ 451 bytes ⋯ "ult_nvar, kwargs...) = 0`.

2022-05-18 13:42 UTC, tmigot commented on src/ADNLPProblems/particles_distribution.jl
> +        end
Could this be equivalent to
```
sum(1/elts[i,j] for i=2:(n-1),j=(i+1):n)
```
?

2022-05-18 13:47 UTC, tmigot commented
Thanks @nathanemac !
Could you rename the `particles_distribution` by `elec` in all the files (and name of the files) ? So that we match the names in CUTEst.

2022-05-18 13:47 UTC, tmigot commented
And add the following comments at the beginning of the file with the model:
```
# Given np electrons, find the equilibrium state distribution of minimal
# Columb potential of the electrons positioned on a conducting sphere

#   This is problem 2 in the COPS (Version 3) collection of 
#   E. Dolan and J. More'
#   see "Benchmarking Optimization Software with COPS"
#   Argonne National Labs Technical Report ANL/MCS-246 (2004)

#   classification OOR2-AN-V-V
```

2022-05-26 13:01 UTC, tmigot requested changes

2022-05-26 13:01 UTC, tmigot commented on src/Meta/elec.jl
> +get_elec_nnln(; n::Integer = default_nvar, kwargs...) = 0 * n + 16
```
get_elec_nnln(; n::Integer = default_nvar, kwargs...) = max(2, div(n,3))
```

2022-05-26 13:01 UTC, tmigot commented on src/Meta/elec.jl
> +get_elec_nequ(; n::Integer = default_nvar, kwargs...) = 0 * n + 16
```
get_elec_nequ(; n::Integer = default_nvar, kwargs...) = max(2, div(n,3))
```

2022-05-26 13:01 UTC, tmigot commented on src/Meta/elec.jl
> +  :contype => :general,
:contype => :quadratic,

2022-05-27 11:50 UTC, tmigot approved these changes
Thanks @nathanemac !

2022-06-01 18:35 UTC, merged