after D.O adds
JuliaSmoothOptimizers/OptimizationProblems.jl pull request #180
Opened 2022-05-17 19:01 UTC by nathanemac

2022-05-18 17:37 UTC, dpo requested changes

2022-05-18 17:37 UTC, dpo commented on src/Meta/marine_population_dynamics.jl
> +    :has_bounds => " ⋯ 461 bytes ⋯ " ult_nvar, kwargs...) = 0
What's this?

2022-05-18 22:37 UTC, tmigot requested changes
Thanks @nathanemac ! I have a couple of comments.

2022-05-18 22:37 UTC, tmigot commented on src/ADNLPProblems/marine_population_dynamics.jl
> +    n > 21 && @warn("arwhead: number of timesteps must be lower than 21. Solving the problem for n=21:")
Replace `arwhead` by `marine`

2022-05-18 22:37 UTC, tmigot commented on src/ADNLPProblems/marine_population_dynamics.jl
> +        return s
```
function f(x)
  return sum(....... for i=1:ns*n)
end
```

2022-05-18 22:37 UTC, tmigot commented on src/ADNLPProblems/marine_population_dynamics.jl
> +        end
c3 = [....... for i=1:(ns*n-1)]

2022-05-18 22:37 UTC, tmigot commented on src/ADNLPProblems/marine_population_dynamics.jl
> +            end
Same comment as for c3

2022-05-18 22:37 UTC, tmigot commented on src/ADNLPProblems/marine_population_dynamics.jl
> +    lcon_c1 = -ones(ns) .- ϵ
Use `ones(T, ns)`, instead of `ones(ns)` and same comment for `zeros` and `rand` below.

2022-07-09 13:18 UTC, dpo commented
@tmigot What is the status here?

2022-07-09 19:46 UTC, tmigot commented
I believe the model here is a simplified version of the one described in `marine.mod` in the archive provided in https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/issues/161 .

2023-07-21 02:52 UTC, closed without merging