Update JuMP syntax to use the new nonlinear interface
JuliaSmoothOptimizers/OptimizationProblems.jl pull request #321
Opened 2024-02-29 12:44 UTC by frapac

I had [to comment out the tests](https://github.com/frapac/OptimizationProblems.jl/blob/fp/nljump/test/runtests.jl#L47-L53) checking that the formulation in JuMP matches those in ADNLPModels.

Apparently, the problem arises when we have `ScalarQuadraticFunction` in the MOI model. Maybe related to: 
https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/102

2024-03-05 00:37 UTC, tmigot commented
Thanks a lot @frapac for the PR. NLPModelsJuMP still doesn't support the quadratic constraints, we lagged behind probably because we did not have a big usage of it. With the new nonlinear JuMP interface, I think we will try to add this quickly. I propose we wait a bit for this PR.

2024-05-23 08:06 UTC, gdalle commented
@amontoison it might be a good time to revisit this PR based on what we discussed yesterday?

2024-05-23 12:48 UTC, amontoison commented
Yes, I need to work on that since a long time.
I could have some bandwidth the end of next week.

2024-06-21 20:44 UTC, amontoison commented
@frapac I released NLPModelsJuMP.jl 0.13.0.
We support `ScalarQuadraticFunction` now.

2024-07-21 20:54 UTC, amontoison commented
@frapac @tmigot 
With the release 0.13.1 of NLPModels.jl, the new nonlinear API of JuMP is supported.
Benoît helped me to fix the last issue today during the Hackathon of JuMP-dev 2024.

2024-07-23 11:15 UTC, tmigot requested changes

2024-07-23 11:15 UTC, tmigot commented on test/runtests.jl
> +  # end
```suggestion
  @testset "Test problems compatibility for $prob" begin
    prob_fn = eval(Meta.parse("PureJuMP.$(prob)"))
    model = prob_fn(n = ndef)
    nlp_jump = MathOptNLPModel(model)
    test_compatibility(prob, nlp_jump, nlp_ad, ndef)
  end
```

2024-09-07 00:51 UTC, tmigot commented
Superseded by #339

2024-09-07 00:51 UTC, closed without merging