Add docs
JuliaSmoothOptimizers/OptimizationProblems.jl pull request #80
Opened 2021-11-11 21:42 UTC by tmigot

Add documentation on the repo and the new feature with the two sets divided in submodules.

We can merge #79 after this :).

2021-11-13 23:01 UTC, abelsiqueira requested changes
Thanks for the PR. I've made some comments.

2021-11-15 13:17 UTC, tmigot commented on docs/src/benchmark.md
> +The function `SolverBenchmarl.bmak_solvers` will run all the problems on the specified solvers and store the results in a `DataFrames`.
Thanks for the comments.

2021-11-15 21:44 UTC, abelsiqueira approved these changes

2021-11-15 21:45 UTC, abelsiqueira commented
Is this the first to merge? I forgot the order. Feel free to merge. Thanks.

2021-11-15 22:19 UTC, merged